version: "3.7"
services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SERVER_ENABLE_GZIP: 'true'
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: 'true'
      GF_USERS_VIEWERS_CAN_EDIT: 'true'
      GF_INSTALL_PLUGINS: natel-plotly-panel
    networks:
      - backend
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_password
    volumes:
      - grafana-storage:/var/lib/grafana
  timescaledb:
    # use pg10, latest supported by grafana timescaledb plugin
    image: timescale/timescaledb:latest-pg10
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_postgres_password
    networks:
      - backend
    ports:
      - "5432:5432"
    secrets:
      - postgres_postgres_password
    volumes:
      - timescaledb-storage:/var/lib/postgresql/data

volumes:
  grafana-storage:
    external: true
  timescaledb-storage:
    external: true

networks:
  backend:

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
  postgres_postgres_password:
    file: ./secrets/postgres_postgres_password.txt
