version: "3.7"
services:
  grafana:
    #image: grafana/grafana:6.0.0
    image: ctberthiaume/grafana:gradients3
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
    environment:
      GF_SERVER_ENABLE_GZIP: 'true'
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: 'true'
      GF_USERS_VIEWERS_CAN_EDIT: 'true'
    networks:
      - backend
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_password
    volumes:
      - grafana-storage:/var/lib/grafana
  timescaledb:
    # use pg10, latest supported by grafana timescaledb plugin
    image: timescale/timescaledb:1.2.2-pg10
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_postgres_password
    networks:
      - backend
    ports:
      - "5432:5432"
    secrets:
      - postgres_postgres_password
    volumes:
      - timescaledb-storage:/var/lib/postgresql/data
  minio:
      image: minio/minio:RELEASE.2019-03-20T22-38-47Z
      command: server /data
      deploy:
        restart_policy:
          condition: any
          delay: 5s
          window: 60s
      environment:
        MINIO_ACCESS_KEY_FILE: minio_access_key
        MINIO_SECRET_KEY_FILE: minio_secret_key
      networks:
        - backend
      ports:
        - "9000:9000"
      secrets:
        - minio_access_key
        - minio_secret_key
      volumes:
        - minio-storage:/data
  ingest:
    #image: ctberthiaume/ingest:gradients3
    image: ingest-minio
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
    environment:
      CURRENT_CRUISE: gradients2  # current cruise name, subfolder of metadata, should be in DBNAMES_FILE
      PGHOST: timescaledb
      PGDATABASE: gradients2  # db for current cruise, should be in dbnames.sh
      PGUSER: postgres  # admin user name
      ROUSER: ocean  # read-only user name
      PGPASSWORD_FILE: /run/secrets/postgres_postgres_password  # postgres admin password
      ROPASSWORD_FILE: /run/secrets/postgres_ro_password  # postgres read-only user password
      MINIO_ACCESS_KEY_FILE: /run/secrets/minio_access_key  # minio admin access key
      MINIO_SECRET_KEY_FILE: /run/secrets/minio_secret_key  # minio admin secret key
      MINIO_ENDPOINT: minio:9000
      MINIO_INPUT_BUCKET: input-data  # bucket for unparsed input data files
      MINIO_PARSED_BUCKET: parsed-data  # bucket for parsed data files
      DBNAMES_FILE: /app/dbnames.txt  # file with cruise DBNAMES array
      METADATA_DIR: /app/metadata  # don't change unless changing source dir layout
      OUTPUT_DIR: /mnt/outputs  # don't change unless changing downstream-storage mount point
    networks:
      - backend
    secrets:
      - postgres_postgres_password
      - postgres_ro_password
      - minio_access_key
      - minio_secret_key
    volumes:
      - downstream-storage:/mnt/outputs
      - ./dockerfiles/ingest/:/app/
    
volumes:
  grafana-storage:
    external: true
  timescaledb-storage:
    external: true
  downstream-storage:
    external: true
  minio-storage:
    external: true

networks:
  backend:
    driver: overlay
    attachable: true

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
  postgres_postgres_password:
    file: ./secrets/postgres_postgres_password.txt
  postgres_ro_password:
    file: ./secrets/postgres_ro_password.txt
  minio_access_key:
    file: ./secrets/minio_access_key.txt
  minio_secret_key:
    file: ./secrets/minio_secret_key.txt
