version: "3.7"
services:
  grafana:
    #image: grafana/grafana:6.0.0
    image: ctberthiaume/grafana:gradients3
    environment:
      GF_SERVER_ENABLE_GZIP: 'true'
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: 'true'
      GF_USERS_VIEWERS_CAN_EDIT: 'true'
    networks:
      - backend
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_password
    volumes:
      - grafana-storage:/var/lib/grafana
  timescaledb:
    # use pg10, latest supported by grafana timescaledb plugin
    #image: timescale/timescaledb:1.2.1-pg10
    image: timescale/timescaledb:1.2.1-pg10
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_postgres_password
    networks:
      - backend
    ports:
      - "5432:5432"
    secrets:
      - postgres_postgres_password
    volumes:
      - timescaledb-storage:/var/lib/postgresql/data
  samba:
    image: ctberthiaume/samba:gradients3
    environment:
      SAMBA_USER: ocean
      SAMBA_PASSWORD_FILE: /run/secrets/samba_password
      SAMBA_SHARE_NAME: dataintegration
    networks:
      - backend
    ports:
      - "139:139"
      - "445:445"
    secrets:
      - samba_password
    volumes:
      - incoming-storage:/data
  ingest:
    image: ctberthiaume/ingest:gradients3
    environment:
      PGHOST: timescaledb
      PGDATABASE: gradients2  # db for current cruise, should be in dbnames.sh
      PGUSER: postgres  # admin user name
      ROUSER: ocean  # read-only user name
      PGPASSWORD_FILE: /run/secrets/postgres_postgres_password
      ROPASSWORD_FILE: /run/secrets/postgres_ro_password
      CURRENT_CRUISE: gradients2  # current cruise name, subfolder of metadata
      DBNAMES_FILE: /app/dbnames.txt  # file with cruise DBNAMES array
    networks:
      - backend
    secrets:
      - postgres_postgres_password
      - postgres_ro_password
    volumes:
      - incoming-storage:/mnt/inputs
      - downstream-storage:/mnt/outputs
      - ./dockerfiles/ingest/:/app/

volumes:
  grafana-storage:
    external: true
  timescaledb-storage:
    external: true
  incoming-storage:
    external: true
  downstream-storage:
    external: true

networks:
  backend:
    driver: overlay
    attachable: true

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
  postgres_postgres_password:
    file: ./secrets/postgres_postgres_password.txt
  postgres_ro_password:
    file: ./secrets/postgres_ro_password.txt
  samba_password:
    file: ./secrets/samba_password.txt
