# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
#deleteDatasources:
#  - name: Graphite
#    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Gradients1
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: timescaledb:5432
  # <string> database user, if used
  user: ROUSER
  # <string> database name, if used
  database: gradients1
  # <bool> enable/disable basic auth
  basicAuth:
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    postgresVersion: 1000
    timescaledb: true
    maxOpenConns: unlimited
    maxIdleConns: 2
    connMaxLifetime: 14400
    timeInterval: 1m
    sslmode: disable
  secureJsonData:
    password: ROPASSWORD
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: Gradients2
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: timescaledb:5432
  # <string> database user, if used
  user: ROUSER
  # <string> database name, if used
  database: gradients2
  # <bool> enable/disable basic auth
  basicAuth:
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    postgresVersion: 1000
    timescaledb: true
    maxOpenConns: unlimited
    maxIdleConns: 2
    connMaxLifetime: 14400
    timeInterval: 1m
    sslmode: disable
  secureJsonData:
    password: ROPASSWORD
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: Gradients3
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: timescaledb:5432
  # <string> database user, if used
  user: ROUSER
  # <string> database name, if used
  database: gradients3
  # <bool> enable/disable basic auth
  basicAuth:
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    postgresVersion: 1000
    timescaledb: true
    maxOpenConns: unlimited
    maxIdleConns: 2
    connMaxLifetime: 14400
    timeInterval: 1m
    sslmode: disable
  secureJsonData:
    password: ROPASSWORD
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
- name: HOT_2019_06_30
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: timescaledb:5432
  # <string> database user, if used
  user: ROUSER
  # <string> database name, if used
  database: hot_2019_06_30
  # <bool> enable/disable basic auth
  basicAuth:
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    postgresVersion: 1000
    timescaledb: true
    maxOpenConns: unlimited
    maxIdleConns: 2
    connMaxLifetime: 14400
    timeInterval: 1m
    sslmode: disable
  secureJsonData:
    password: ROPASSWORD
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
