table = "par"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "par"
type = "real"

[[fields]]
index = 2
name = "temp"
type = "real"

[[fields]]
index = 3
name = "salinity"
type = "real"


