table = "eco"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "CHL"
type = "real"

[[fields]]
index = 2
name = "Scattering"
type = "real"

[[fields]]
index = 3
name = "CDOM"
type = "real"


