table = "lisst"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "V135um"
type = "real"

[[fields]]
index = 2
name = "V160um"
type = "real"

[[fields]]
index = 3
name = "V189um"
type = "real"

[[fields]]
index = 4
name = "V223um"
type = "real"

[[fields]]
index = 5
name = "V263um"
type = "real"

[[fields]]
index = 6
name = "V311um"
type = "real"

[[fields]]
index = 7
name = "V367um"
type = "real"

[[fields]]
index = 8
name = "V433um"
type = "real"

[[fields]]
index = 9
name = "V511um"
type = "real"

[[fields]]
index = 10
name = "V603um"
type = "real"

[[fields]]
index = 11
name = "V711um"
type = "real"

[[fields]]
index = 12
name = "V839um"
type = "real"

[[fields]]
index = 13
name = "V990um"
type = "real"

[[fields]]
index = 14
name = "V1169um"
type = "real"

[[fields]]
index = 15
name = "V1379um"
type = "real"

[[fields]]
index = 16
name = "V1627um"
type = "real"

[[fields]]
index = 17
name = "V1920um"
type = "real"

[[fields]]
index = 18
name = "V2266um"
type = "real"

[[fields]]
index = 19
name = "V2674um"
type = "real"

[[fields]]
index = 20
name = "V3156um"
type = "real"

[[fields]]
index = 21
name = "V3724um"
type = "real"

[[fields]]
index = 22
name = "V4395um"
type = "real"

[[fields]]
index = 23
name = "V5186um"
type = "real"

[[fields]]
index = 24
name = "V6120um"
type = "real"

[[fields]]
index = 25
name = "V7222um"
type = "real"

[[fields]]
index = 26
name = "V8522um"
type = "real"

[[fields]]
index = 27
name = "V10056um"
type = "real"

[[fields]]
index = 28
name = "Cmd_sm"
type = "real"

[[fields]]
index = 29
name = "Cmd_med"
type = "real"

[[fields]]
index = 30
name = "Cmd_lg"
type = "real"


