table = "po4"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "sample"
type = "real"

[[fields]]
index = 2
name = "depth"
type = "real"

[[fields]]
index = 3
name = "lat"
type = "real"

[[fields]]
index = 4
name = "lon"
type = "real"

[[fields]]
index = 5
name = "po4"
type = "real"


