table = "pp"
null = "NaN"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "lat"
type = "real"

[[fields]]
index = 2
name = "lon"
type = "real"

[[fields]]
index = 3
name = "sst"
type = "real"

[[fields]]
index = 4
name = "salinity"
type = "real"

[[fields]]
index = 5
name = "PP"
type = "real"

[[fields]]
index = 6
name = "over_point7_micron_P"
type = "real"


