table = "o2ar"
null = "NaN"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "lat"
type = "real"

[[fields]]
index = 2
name = "lon"
type = "real"

[[fields]]
index = 3
name = "temp"
type = "real"

[[fields]]
index = 4
name = "salinity"
type = "real"

[[fields]]
index = 5
name = "bio_sat"
type = "real"

[[fields]]
index = 6
name = "NCP"
type = "real"

[[fields]]
index = 7
name = "O2gasex"
type = "real"


