table = "tsg_par"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "lat"
type = "real"

[[fields]]
index = 2
name = "lon"
type = "real"

[[fields]]
index = 3
name = "conductivity"
type = "real"

[[fields]]
index = 4
name = "salinity"
type = "real"

[[fields]]
index = 5
name = "ocean_tmp"
type = "real"

[[fields]]
index = 6
name = "par"
type = "real"


