table = "underway"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "par"
type = "real"

[[fields]]
index = 2
name = "lat"
type = "real"

[[fields]]
index = 3
name = "lon"
type = "real"

[[fields]]
index = 4
name = "heading"
type = "real"

[[fields]]
index = 5
name = "speed"
type = "real"

[[fields]]
index = 6
name = "bow_temp"
type = "real"

[[fields]]
index = 7
name = "conductivity"
type = "real"

[[fields]]
index = 8
name = "salinity"
type = "real"

[[fields]]
index = 9
name = "lab_temp"
type = "real"

[[fields]]
index = 10
name = "fluor"
type = "real"