{
 "title": "HOT_2019_06_30 by Time",
 "time": { "from": "2019-06-25T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "PAR (mVolts)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(par) AS \"par\"\nFROM par\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Speed (knots)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(knots) AS \"knots\"\nFROM track\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ocean Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(ocean_temp) AS \"ocean_temp\"\nFROM uthsl\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Salinity (PSU)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(salinity) AS \"salinity\"\nFROM uthsl\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperature (y) vs Salinity (x)",
   "type": "armbrustlab-2dscatter-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(salinity) AS \"TS\"\nFROM uthsl_geo\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(ocean_temp) AS \"TS\"\nFROM uthsl_geo\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prochlorococcus abundance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(abundance) AS \"pro\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'prochloro'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prochlorococcus diameter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(diam_mid) AS \"pro\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'prochloro'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Synechococcus abundance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(abundance) AS \"syn\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'synecho'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Synechococcus diameter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(diam_mid) AS \"syn\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'synecho'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Picoeukaryotes abundance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(abundance) AS \"pico\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'picoeuk'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Picoeukaryotes diameter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(diam_mid) AS \"pico\"\nFROM seaflow740\nWHERE\n  $__timeFilter(\"time\") AND\n  pop = 'picoeuk'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}