table = "uthsl"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "ocean_temp"
type = "real"

[[fields]]
index = 2
name = "conductivity"
type = "real"

[[fields]]
index = 3
name = "salinity"
type = "real"

[[fields]]
index = 4
name = "remote_temp"
type = "real"


