table = "seaflow751"
null = "NA"
[[fields]]
index = 0
name = "time"
type = "time"

[[fields]]
index = 1
name = "lat"
type = "real"

[[fields]]
index = 2
name = "lon"
type = "real"

[[fields]]
index = 3
name = "temp"
type = "real"

[[fields]]
index = 4
name = "salinity"
type = "real"

[[fields]]
index = 5
name = "conductivity"
type = "real"

[[fields]]
index = 6
name = "par"
type = "real"

[[fields]]
index = 7
name = "stream_pressure"
type = "real"

[[fields]]
index = 8
name = "file_duration"
type = "real"

[[fields]]
index = 9
name = "event_rate"
type = "real"

[[fields]]
index = 10
name = "opp_evt_ratio"
type = "real"

[[fields]]
index = 11
name = "pop"
type = "text"
groupby = true

[[fields]]
index = 12
name = "n_count"
type = "real"

[[fields]]
index = 13
name = "chl_small"
type = "real"

[[fields]]
index = 14
name = "pe"
type = "real"

[[fields]]
index = 15
name = "fsc_small"
type = "real"

[[fields]]
index = 16
name = "diam_lwr"
type = "real"

[[fields]]
index = 17
name = "diam_mid"
type = "real"

[[fields]]
index = 18
name = "diam_upr"
type = "real"

[[fields]]
index = 19
name = "Qc_lwr"
type = "real"

[[fields]]
index = 20
name = "Qc_mid"
type = "real"

[[fields]]
index = 21
name = "Qc_upr"
type = "real"

[[fields]]
index = 22
name = "quantile"
type = "real"

[[fields]]
index = 23
name = "flag"
type = "real"

[[fields]]
index = 24
name = "flow_rate"
type = "real"

[[fields]]
index = 25
name = "flow_rate_se"
type = "real"

[[fields]]
index = 26
name = "abundance"
type = "real"

[[fields]]
index = 27
name = "abundance_se"
type = "real"


